server :
  port : 8080

spring:
  application:
    name: morent

  datasource:
    url: jdbc:postgresql://localhost:5432/morent
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12345

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: update
      show-sql: true


  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: group-id
      auto-offset-reset: earliest
    producer:
      retries: 0
    template:
      default-topic: notification-topic

stripe:
  api:
    key: stripe_api_key_here



